
text_extensions: [ 'css', 'erb', 'haml', 'htm', 'html', 'js', 'less', 'markdown', 'md', 'php', 'rb', 'sass', 'scss', 'txt', 'xhtml', 'xml' ]

output_dir: output

index_filenames: [ 'index.html' ]

enable_output_diff: false

data_sources:
  -
    type: filesystem_unified
    items_root: /
    layouts_root: /

watcher:
  dirs_to_watch: [ 'content', 'layouts', 'lib' ]
  files_to_watch: [ 'config.yaml', 'Rules' ]
  notify_on_compilation_success: true
  notify_on_compilation_failure: true

deploy:
  default:
    options: [ '-glpPrtvz', '--exclude=".git"', --exclude=".DS_Store" ]
    dst: "linode:/srv/williamyoumans.com/public"
    kind: "rsync"